# Generated by Django 6.0.3 on 2026-04-06 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='IFPMEB', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('primary_color', models.CharField(default='#1d3557', max_length=20)),
                ('secondary_color', models.CharField(default='#ffb703', max_length=20)),
                ('accent_color', models.CharField(default='#457b9d', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('text_color', models.CharField(default='#1d3557', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('hero_content', models.JSONField(blank=True, default=dict)),
                ('flash_info', models.JSONField(blank=True, default=dict)),
                ('enabled_sections', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('features', models.JSONField(default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='core.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
