# Generated by Django 6.0.3 on 2026-04-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('program', models.CharField(max_length=255)),
                ('result_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
