# Generated by Django 6.0.3 on 2026-04-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='career_prospects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='objectives',
            field=models.TextField(blank=True),
        ),
    ]
