# Generated by Django 6.0.3 on 2026-04-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_formation_career_prospects_formation_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
