# Generated by Django 6.0.3 on 2026-04-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academicevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='foundation_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission',
            field=models.TextField(blank=True),
        ),
    ]
