# Generated by Django 6.0.3 on 2026-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='admission_requirements',
            field=models.TextField(blank=True),
        ),
    ]
