# Generated by Django 6.0.3 on 2026-04-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_admission_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('formation', models.CharField(max_length=255)),
                ('status_type', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Contacté', 'Contacté'), ('Inscrit', 'Inscrit')], default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
