# Generated by Django 6.0.3 on 2026-04-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_inscription_alter_academicevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='total_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
